name: Java CI with Maven
on:
  push:
    branches:
      - "main"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-services:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Build Auth Service with Maven
        run: |
          cd authusers
          mvn -B package
      - name: Build Todolist Service with Maven
        run: | 
          cd todolist
          mvn -B package
      - name: Build Notification Service with Maven
        run: |
          cd notifications
          mvn -B package
  publish-docker-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: maven
    - name: Build Auth Service with Maven
      run: |
        cd authusers
        mvn -B package
    - name: Extract metadata (tags, labels) for Docker
      id: meta-auth
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}/authusers
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: /authusers/.
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta-auth.outputs.tags }}
        labels: ${{ steps.meta-auth.outputs.labels }}
